apiVersion: v1
kind: Service
metadata:
  name: k8s-js-app-service
spec:
  selector:
    app: k8s-js-app
  ports:
    - protocol: TCP
      port: 80        # external port
      targetPort: 3000  # container app port
  type: NodePort   # or LoadBalancer if using cloud
